### ISSUE TITLE
tutorial first mod not showing log

### ISSUE THREAD

**Issue by swingguy0** [mroshaw/mroshaw.github.io#2]
Hello, thank you very much for creating this tutorial. It was invaluable. I followed everything through to the first log entry that should show up with the knife, but it wasn't showing up. I think that perhaps I had to check more boxes in the mod settings section of the menu to show more logs or something. 

Then when I tried to do the mod menu settings addition there were errors showing up and it wouldn't work. I know I'm being very general but this was 2 days ago when it happened. I instead found your source code for the seatruck speed increase and copied that and am working off of that for my mod creation.

**Comment by mroshaw** [comment]
Hi!

I'm not sure I understand the issue. What "log entry" are you talking about? What were the "errors" that you saw when you added the "mod settings section"?

The full tutorial mod is on my GitHub, so try referring to that code and see if it's any different to yours:

[https://github.com/mroshaw/BeginnersGuideModSubnautica](https://github.com/mroshaw/BeginnersGuideModSubnautica)

As you've not included any detail of the log you're expecting, the errors that you saw, or any information that could help me make any changes, there's not a lot I can do to resolve this.

**Comment by swingguy0** [comment]
I can see what you mean. I'm starting my next semester of school and may
not get to it until much later.

Best Regards,

Swingguy0
Collin Evans
***@***.***

**Comment by mroshaw** [comment]
Can't replicate and no further info provided.

**Comment by DanDoes** [comment]
Commenting on a very old issue, but I _also_ had trouble with this just now, and I think I can shed some light on it:

The 'knife' logs don't show up because on [this step](https://mroshaw.github.io/Subnautica/yourfirstmod/codingthemod.html) of the tutorial, the log messages in the Plugin are `LogInfo`, but the Knife ones are `LogDebug`, and for a new setup, Debug logs aren't output to the log file. I couldn't tell if my mod was working or not because of this.

Luckily, people in Discord were very [helpful](https://discord.com/channels/324207629784186882/324207629784186882/1236391006019260527):
> Set LogLevels to All in BepInEx/config/BepInEx.cfg

> There are a few LogLevels properties, make sure to set the one under the Logging.Disk if you want the LogOutput.log file specifically to include all log levels.
